### ISSUE TITLE
Odin's Power NOT WORKING

### ISSUE THREAD

**Issue by sanny1128** [rathena/rathena#2122]
rAthena Hash: 4a004ad
Client Date: 2017-01-25RagexeRE
Server Mode: Renewall
Description of Issue: Some skills are not increasing the character ATK or the damage.

Result: When i use skills like Odin's Power my ATK has increase(show in status window) but the final damage is not affected AND my MATK does not increase(not show in status window)

Expected Result: I think the damage should be increased or the ATK should be increased on the status window.

How to Reproduce: Create a Archbishop, type @useskill 2537 2 TEST, use the skill on yourself(Odin's Power).

My tests:

*Odin's Power Skill ~ Not increasing ATK and MATK
BEFORE
<img width="1024" alt="1" src="https://cloud.githubusercontent.com/assets/26641915/25772100/8e9b4314-3295-11e7-8ea4-7248675a2ddf.png">
AFTER
<img width="1024" alt="3" src="https://cloud.githubusercontent.com/assets/26641915/25772103/a0c26004-3295-11e7-9f14-5f24852e15f8.png">
<img width="1024" alt="2" src="https://cloud.githubusercontent.com/assets/26641915/25772104/a2d81a64-3295-11e7-84c4-3dda7d0663e8.png">

**Comment by RadianFord** [comment]
I think this issue was fixed lately. 

1. https://github.com/rathena/rathena/issues/2120
2. https://github.com/rathena/rathena/issues/2118

**Comment by sanny1128** [comment]
＠RadianFord BUT I upgrade emulator to latest revision and the issue still exists

**Comment by RadianFord** [comment]
@sanny1128 let's wait till they can confirm this Im not using the latest one..

**Comment by aleos89** [comment]
It increases WATK. From your screen shot you're not wearing any weapon. Please remember too, as stated before, not all status bonuses show up in the status window.

**Comment by sanny1128** [comment]
@aleos89  OK I retest it's work fine
sorry and thanksss~~
