### ISSUE TITLE
Geffen Magic Tournament Error

### ISSUE THREAD

**Issue by hendra814** [rathena/rathena#2598]
* **rAthena Hash**: lastest

* **Client Date**: 2015-11-04

* **Server Mode**: renewal

* **Description of Issue**: error on script geffen magic tournament
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**: 
  
  

here ss error in map console
![1](https://user-images.githubusercontent.com/9587609/32699211-bc55986a-c7e4-11e7-816f-5a0508e9fc48.jpg)
![2](https://user-images.githubusercontent.com/9587609/32699213-bd8e5190-c7e4-11e7-8440-cfd75a96328f.jpg)
![3](https://user-images.githubusercontent.com/9587609/32699214-be05c946-c7e4-11e7-9d7f-7ea479ffda21.jpg)

**Comment by mazvi** [comment]
i dont find E_THX E_HMM on https://github.com/rathena/rathena/blob/master/npc/custom/official/GeffenMagicTournament.txt

i think you not update the GeffenMagicTournament.txt to latest update on this git hub?

can you replace your GeffenMagicTournament.txt

with this script? https://github.com/rathena/rathena/blob/master/npc/custom/official/GeffenMagicTournament.txt

**Comment by hendra814** [comment]
@mazvi 
already do that but still pop up the same error.

**Comment by mazvi** [comment]
What your method update git merge hash or git pull?

**Comment by hendra814** [comment]
I'm using tortoise svn, used svn update.

**Comment by Jeybla** [comment]
cd08915530e4156fdcbba95b6f3966ff9ddbd520 should fix it.
The error seems to be caused by the conversion script we used.
Just some wrongly placed parentheses, we didn't see because the script is not loaded by default. Thanks for the input @hendra814 and @mazvi

**Comment by hendra814** [comment]
but the warning still appear
![image](https://user-images.githubusercontent.com/9587609/32717603-c8e43ade-c88c-11e7-9668-a3463c0d4ff2.png)

**Comment by Jeybla** [comment]
That looks like your custom NPCs are using the old constants. You can either replace them by hand or use this conversion tool:
https://github.com/Jeybla/rathena/blob/emotion_test/tools/convert_emotions.py
I recommend to set `convert_folders` to your custom npc folder:
`convert_folders = ["/path/to/your/custom/npcs"]`

**Comment by hendra814** [comment]
@Jeybla 
are have guide to use the conversion tool?
how do i run the script, is copy paste and make bat file?

**Comment by Jeybla** [comment]
It's a python3 script. If you're on Linux you can just put it in your rathena/tools folder and execute(`./convert_emotions.py`) it.
On windows you should be able to run it with `python3 convert_emotions.py` from the command line after installing python3.
https://docs.python.org/3/using/windows.html
