### ISSUE TITLE
Map server crash after skill "Dragon Tail"

### ISSUE THREAD

**Issue by attackjom** [rathena/rathena#3872]
* **https://github.com/rathena/rathena/commit/6bea2da34d19e9c6d6d1e9d2af2a36d772c129ba**: 

* **2018-05-30**: 

* **Renewal**: 

* **Description of Issue**: 
  * Result: 
  * Expected Result: 
  * How to Reproduce: 
  * Official Information:
  

* **Modifications that may affect results**:

**Comment by aleos89** [comment]
Can you please provide the core dump? Thanks.

**Comment by attackjom** [comment]
Sorry guy. What do you mean about core dump. Sorry for stupid question but I’m too beginner in rathena.

**Comment by aleos89** [comment]
Check out the [wiki](https://github.com/rathena/rathena/wiki/Crash_Logging) on how to get more information on the core dumps depending on your OS.

**Comment by attackjom** [comment]
` 	0030fae4()	Unknown
 	[Frames below may be incorrect and/or missing]	Unknown
 	map-server.exe!map_foreachinrangeV(int(*)(block_list *, char *) func, block_list * center, short range, int type, char * ap, bool wall_check) Line 674	C++
>	map-server.exe!map_foreachinshootrange(int(*)(block_list *, char *) func, block_list * center, short range, int type, ...) Line 713	C++
 	map-server.exe!skill_castend_id_check(block_list * src, block_list * target, unsigned short skill_id, unsigned short skill_lv) Line 11154	C++
 	map-server.exe!skill_castend_id(int tid, __int64 tick, int id, int data) Line 11340	C++
 	map-server.exe!do_timer(__int64 tick) Line 374	C++
 	map-server.exe!main(int argc, char * * argv) Line 367	C++
 	[External Code]	`

**Comment by attackjom** [comment]
`0030fae4()	Unknown
[Frames below may be incorrect and/or missing]	Unknown
map-server.exe!map_foreachinrangeV(int(*)(block_list *, char *) func, block_list * center, short range, int type, char * ap, bool wall_check) Line 674	C++
map-server.exe!map_foreachinshootrange(int(*)(block_list *, char *) func, block_list * center, short range, int type, ...) Line 713	C++
map-server.exe!skill_castend_id_check(block_list * src, block_list * target, unsigned short skill_id, unsigned short skill_lv) Line 11154	C++
map-server.exe!skill_castend_id(int tid, __int64 tick, int id, int data) Line 11340	C++
map-server.exe!do_timer(__int64 tick) Line 374	C++
map-server.exe!main(int argc, char * * argv) Line 367	C++
[External Code]	`

**Comment by Lemongrass3110** [comment]
Update your server. This was fixed not long ago.

**Comment by attackjom** [comment]
https://github.com/rathena/rathena/pull/3874
I merge this pull already ,  however mapserver-crash still persist.

**Comment by teededung** [comment]
I pulled https://github.com/rathena/rathena/pull/3874 and no crash. @attackjom Have you compiled it?
@aleos89 When I used Dragon Tail skill, under chat box was showed that "Skill has failed".

How to Reproduce: 
EQ:
End of Horizon (28200)
Dragon Tail Missile (7665)

1. Use Crimson Maker on target
2. Use Dragon Tail

Official Video: https://youtu.be/9NK2EiyWskw?t=9

**Comment by aleos89** [comment]
@teededung Thanks. I confirmed it and fixed it in the same PR.
