### ISSUE TITLE
[Crashes Issues] Client 2014-10-22 

### ISSUE THREAD

**Issue by limitro** [rathena/rathena#484]
Hi.
I use the latest rA git and uses 2014-10-22 client.

Here is some bugs that causes by it so far:

When type @job ingame, the client it freeze and then crash.

When killing a monster, the client freeze game crashes.

The booking system, after create a recruit, 
and you search quickly, it will crash client.
It will even crash if you cancel too quick.

None of those provided any additional error msg or so...
I do not know how to find out the reason behind this issue.

Anyonw knows how to solve?

**Comment by limitro** [comment]
The when killing a monster crash is solved if you remove the Diff "Increase Attack Display".

If you type @go in the chat, the client will also crash.

It seems to do with the Chat Box somehow.

**Comment by reigneil** [comment]
what i think is... this is nothing to do with the server. it is more on the client itself.
better to debug it yourself like update your client and/or set it to default setting. (no custom grf/folder) and see what it can do... or dont apply too many custom patches on your exe.

**Comment by aleos89** [comment]
As @reigneil stated, it's mainly the client at fault. It's not a stable client and we can try to add work arounds server side to prevent some crashes, but some are just inevitable. While testing Roulette myself, @cydh, and @icxbb-xx crashed continuously just trying to open/play with Roulette.

**Comment by limitro** [comment]
Altho, I had no issues with the roulette crash or so, so far.

But, I edited the text for @go info, and @job info in the help.txt , and some text worked...so it's like a chat pattern that will crash the client...

Any idea how I can debug aside for manually doing testings? Any programs or so?

**Comment by icxbb-xx** [comment]
@limitro test again fixed in latest rA

**Comment by limitro** [comment]
@icxbb-xx , Umm I'm not sure.
But, none of the reported were fixed? :o: 
still crashes.

**Comment by limitro** [comment]
Another client side bug...
When you are a merchant, and Alt + W will not open your Cart inventory. :(

**Comment by limitro** [comment]
Hi, Thanks.
Now the @go @job etc will not crash.
Altho, it now doesnt show the full msg in the Chat Window.
![error3](https://cloud.githubusercontent.com/assets/9300961/8362420/faa5d76c-1b78-11e5-9d16-fa1bd668197f.png)


And, the Booking system crash.
Is that if you make a Booking, and then directly click on search, or cancel etc.  Will cause crash.

But, if you walk around, teleport etc and then does that, nothing will happen. <3

**Comment by anacondaqq** [comment]
as i know, town names from @go command available in help.txt
hmm, let me check. Do yo u have client + data.grf for tests only?

**Comment by icxbb-xx** [comment]
fixed in https://github.com/rathena/rathena/commit/bd1b07285b583aba19870ded387a4c99384f5655

**Comment by limitro** [comment]
@icxbb-xx , is this fixed? 
I got the latest patch, in the clif.c and still the same :o: 
Does not show whole msg, just like 3 lines.

**Comment by icxbb-xx** [comment]
Oh sorry my bad
fixed in https://github.com/rathena/rathena/commit/58c2b773a287dd35de3b1a5ed2d62cc4d3cd42fc

@limitro try check again
thank you for report

**Comment by limitro** [comment]
@icxbb-xx , Same results.
Displaying the msg, bit not whole only 3 lines.

**Comment by icxbb-xx** [comment]
I have test show full text
![easycapture1](https://cloud.githubusercontent.com/assets/3500355/8392476/543096ac-1d16-11e5-8b19-a9fe572d8725.jpg)

**Comment by limitro** [comment]
Hmmm...maybe I disabled the "chat box msg extend"?
Maybe because of that reason? :O

**Comment by gengstergile** [comment]
hi. i updated to the latest patch but encounter the same error (client went crash). but then i followed @icxbb-xx fix from bd1b072 patch. it gave me the same results as @limitro. please help me. thanks.

**Comment by limitro** [comment]
Thank god, I'm not the only one.

**Comment by gengstergile** [comment]
ok i got it fix. heres my solution

#if PACKETVER == 20141022
		/** for some reason game client crashes depending on message pattern (only for this packet) **/
		/** so we redirect to ZC_NPC_CHAT **/
		//clif_colormes(fd, color_table[COLOR_DEFAULT], mes);
		char *message, *line;
		message = aStrdup(mes);
		line = strtok(message, "\n");
		while(line != NULL) {
		unsigned long color = (color_table[COLOR_DEFAULT] & 0x0000FF) << 16 | (color_table[COLOR_DEFAULT] & 0x00FF00) | (color_table[COLOR_DEFAULT] & 0xFF0000) >> 16; // RGB to BGR
		unsigned short len = strnlen(mes, 255);

		if (len > 0) { 
			WFIFOHEAD(fd, 13 + len);
			WFIFOW(fd, 0) = 0x2C1;
			WFIFOW(fd, 2) = 13 + len;
			WFIFOL(fd, 4) = 0;
			WFIFOL(fd, 8) = color;
			safestrncpy((char *)WFIFOP(fd,12), line, len + 1);
			WFIFOSET(fd, WFIFOW(fd, 2));
			}
			line = strtok(NULL, "\n");
		}
		aFree(message);
#else

**Comment by limitro** [comment]
@gengstergile  , which file did you edit?

**Comment by gengstergile** [comment]
@limitro edited clif.c
here..
change the format to .diff

**Comment by limitro** [comment]
Awesome <3  Worked fine for me ^!

**Comment by gengstergile** [comment]
good to know its working for you too...

**Comment by icxbb-xx** [comment]
fixed in https://github.com/rathena/rathena/commit/88cfff01e6b06cee8ed1b890c6c9a5ae23b8882d

thankyou @gengstergile , @limitro
