### ISSUE TITLE
Map Server Crashed when changing specific job

### ISSUE THREAD

**Issue by bgamez23** [rathena/rathena#6570]
* **rAthena Hash**: 0fc05cec70d3adbc9e500b5c6401a64adc27759c

* **Client Date**: 2021-11-17

* **Server Mode**: Renewal

* **Description of Issue**: Map server crashed when switch to 4051 Death Knight and 4052 Dark Collector
  * Result: ![image](https://user-images.githubusercontent.com/1854368/151395582-829ea299-dd58-4cb5-994f-3f7ee4649b11.png)
  * Expected Result: 
  * How to Reproduce: Just switch job to 4051 or 4052 job then the map server will crashed
  * Official Information: 
  

* **Modifications that may affect results**:

**Comment by Lemongrass3110** [comment]
Update your server.
This was fixed already.
Those jobs were removed from the YAML database.

**Comment by bgamez23** [comment]
![image](https://user-images.githubusercontent.com/1854368/151503082-cb5b4cb7-5a3a-4e43-94be-fb5db96a5d2c.png)
i think its up to date but still exist.

**Comment by bgamez23** [comment]
> Update your server. This was fixed already. Those jobs were removed from the YAML database.

the bug still do exist even on the latest version of rathena.
178e71d2f90626601c54e3e447c0dab9847e2711
newly download, newly database

you can still see the option for the job of Death Knight and Dark Collector. if you select it map server still crashing.
![screenrAthena004](https://user-images.githubusercontent.com/1854368/151690908-c6cd4dc7-1704-49cc-928f-c7c3716e35f4.jpg)
![screenrAthena006](https://user-images.githubusercontent.com/1854368/151690917-2e678ad1-6d4b-403f-9e79-4683cccb1844.jpg)
![screenrAthena005](https://user-images.githubusercontent.com/1854368/151690912-d97c5368-9295-47b4-a0f2-86b3aa9de30b.jpg)
![image](https://user-images.githubusercontent.com/1854368/151690961-b5fa78d4-926f-4310-b149-0908804f7b1b.png)

**Comment by Atemo** [comment]
Death Knight and 4052 Dark Collector

**Comment by bgamez23** [comment]
there is another map crashed when i try to switch another job like 4308 Spirit Handler.

im using latest githash 181bc0e856a814000fbff6f886a5e2b364ce42e0
![image](https://user-images.githubusercontent.com/1854368/152043924-c0d69c73-89a9-458d-91d2-81e5b8e118f4.png)
![screenrAthena003](https://user-images.githubusercontent.com/1854368/152043961-114da649-6a1f-4102-ad39-112cf2b7222c.jpg)
![screenrAthena004](https://user-images.githubusercontent.com/1854368/152043964-e0e686c8-1bdc-4b38-bd76-f82ab1c8d738.jpg)
![screenrAthena005](https://user-images.githubusercontent.com/1854368/152043965-8c021361-c2d8-42b7-a1db-f4b1e54ad3a7.jpg)
![screenrAthena006](https://user-images.githubusercontent.com/1854368/152043971-25361736-a76c-44da-a014-b5cb04d32c69.jpg)

**Comment by bgamez23** [comment]
map crashed for 4308 Spirit Handler.
6ccf15330e181ee4ce3bb061a52e1c2667b182a5

**Comment by bgamez23** [comment]
![screenrAthena000](https://user-images.githubusercontent.com/1854368/152563552-ee075ea3-966f-4873-b5ab-27336f85de04.jpg)
![screenrAthena001](https://user-images.githubusercontent.com/1854368/152563620-75bd400c-70d3-4bd0-8974-9ffbb8b1f1f4.jpg)
![screenrAthena002](https://user-images.githubusercontent.com/1854368/152563639-d6ace7e3-4ac2-4c91-ad0a-c29482fe5578.jpg)
![screenrAthena003](https://user-images.githubusercontent.com/1854368/152563654-ca4dce38-d7c6-4bc7-aff8-bcb783a9d160.jpg)
