### ISSUE TITLE
Clone monster only take 1 damage

### ISSUE THREAD

**Issue by vietlubu** [rathena/rathena#7579]
### rAthena Hash

96f0f77d4

### Client Date

2021-11-03

### Server Mode

Renewal

### Result

I'm using the clone function to make a clone. But don't know why my clone attacked too fast and I only deal 1 damage to the clone.
Already use a stronger character but Novice clone still taken 1 damage.

```c
clone "payon", 167,225, "Test Clone::CloneDie", getcharid(0);
```

Same issue with `@clone` command

![clone](https://user-images.githubusercontent.com/9859310/216801061-f829e0ab-0c0d-4499-8fd3-7128406f6f69.gif)

Use stronger character:
![Screenshot 2023-02-05 at 11 08 40](https://user-images.githubusercontent.com/9859310/216801067-b379bd5e-019f-4273-a047-9fee4f076977.png)

### Expected Result

The clone should be have same original character's attributes

### How to Reproduce

Use clone function
```c
clone "payon", 167,225, "Test Clone::CloneDie", getcharid(0);
```

### Official Information

None

### Modifications that may affect results

None

**Comment by Lemongrass3110** [comment]
Problem seems to originate from mob.cpp::mob_clone_spawn:
```cpp
	if (mode) //User provided mode.
		status->mode = mode;
	else if (flag&1) //Friendly Character, remove looting.
		status->mode = static_cast<enum e_mode>(status->mode&(~MD_LOOTER));
```

@aleos89 this looks like an issue from the "new" mob modes. I guess the logic that worked before introducing the new modes doesnt work anymore. So guess we need to check back what the "default" mode was back then and define and maybe use one of the MONSTER_TYPE_* for it by default?

**Comment by Lemongrass3110** [comment]
Full sample script:
```
prontera,150,150,4	script	Cloner	989,{
	clone "prontera",150,150, "Cloner::OnCloneDie", getcharid(0);
	end;

OnCloneDie:
	end;
}
```

**Comment by iberryRO** [comment]
I think this problem persists.
And I also think that clones will not be affected by any skill of the player.

![image](https://github.com/rathena/rathena/assets/59070443/11832910-6899-451e-8e4f-6f04194c184a)
![image](https://github.com/rathena/rathena/assets/59070443/c861fc6c-39a9-4c8f-a037-0a0b1e663f13)

rAthena Hash : [8d49496177f0c01d00dd0cabfaed2567aea4e527](https://github.com/rathena/rathena/commit/8d49496177f0c01d00dd0cabfaed2567aea4e527)

**Comment by fab10Carvalho** [comment]
> I think this problem persists. And I also think that clones will not be affected by any skill of the player.
> 
> ![image](https://user-images.githubusercontent.com/59070443/256940164-11832910-6899-451e-8e4f-6f04194c184a.png) ![image](https://user-images.githubusercontent.com/59070443/256940866-c861fc6c-39a9-4c8f-a037-0a0b1e663f13.png)
> 
> rAthena Hash : [8d49496177f0c01d00dd0cabfaed2567aea4e527](https://github.com/rathena/rathena/commit/8d49496177f0c01d00dd0cabfaed2567aea4e527)

![image](https://github.com/rathena/rathena/assets/112716645/103512f1-6e77-4261-b92d-3418cd035eb1)

Confiem issue not sloved!!

**Comment by zdurexz** [comment]
Confirm
![image](https://github.com/rathena/rathena/assets/59825922/260cac86-0042-41a3-9832-543ee54310fa)

**Comment by iberryRO** [comment]
> I think this problem persists. And I also think that clones will not be affected by any skill of the player.
> 
> ![image](https://user-images.githubusercontent.com/59070443/256940164-11832910-6899-451e-8e4f-6f04194c184a.png) ![image](https://user-images.githubusercontent.com/59070443/256940866-c861fc6c-39a9-4c8f-a037-0a0b1e663f13.png)
> 
> rAthena Hash : [8d49496177f0c01d00dd0cabfaed2567aea4e527](https://github.com/rathena/rathena/commit/8d49496177f0c01d00dd0cabfaed2567aea4e527)


ok i fixed it.

**Comment by vietlubu** [comment]
@aleos89, On the lastest rathena version this issue is back
![image](https://github.com/rathena/rathena/assets/9859310/d47fa754-2a3a-4b78-8751-08142406f684)
