### ISSUE TITLE
can't move after summoning homunculus.

### ISSUE THREAD

**Issue by Varyss** [rathena/rathena#770]
using d2d1fd21d3d4187f04b66744bf249c08947aefcf
client 2013-12-23c

so bad that anyone that logs in while having homunculus can't do anything.

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/bc8a12f2c68be425eba5eec54966e3692420d067

Thank you for report @Varyss

**Comment by Varyss** [comment]
thanks @icxbb-xx . but I'm still seeing some issues. the sp shows 0/current instead of current/max and the exp is much higher than how they should be.

**Comment by icxbb-xx** [comment]
Fixed in https://github.com/rathena/rathena/commit/a47af467f3241c6e2227c4dcc89570c7644eb712

sorry i forgot to this XD
